# Generated by Django 6.0.5 on 2026-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capesign',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
