# Generated by Django 6.0.5 on 2026-06-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='capesign',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
